version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: node
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
    entrypoint: node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx: 
    restart: always
    build:
      context: nginx
    container_name: nginx
    entrypoint: sh -c "sleep 10 && dockerize -wait tcp://app:3000 -timeout 60s"
    networks:
      - node-network
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - db
      - app

    
networks:
  node-network:
    driver: bridge

